- name: Create Directory keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0644'

- name: Download Docker GPG Key
  get_url:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker GPG Key
  shell: gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Add Docker apt Repositry
  apt_repository:
    repo: "https://mirrors.bfsu.edu.cn/docker-ce/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker and Containerd
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
