- name: intialization of kubernetes installation
  host: all

  tasks:
  - name: turn off swap
    shell:
      cmd: sudo swapoff -a

  - name: before install containerd and docker
    shell: |
      modprobe overlay && modprobe br_netfilter
      touch /etc/modules-load.d/containerd.conf
      touch /etc/sysctl.d/99-kubernetes-cri.conf
    become: true

  - name: kernel-module - containerd
    blockinfile:
      path: "/etc/modules-load.d/containerd.conf"
      block: |
        overlay
        br_netfilter
    become: true

  - name: kernel-module - kubernetes-cri
    blockinfile:
      path: "/etc/sysctl.d/99-kubernetes-cri.conf"
      block: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
    become: true

  - name: enable ip-forwarding
    blockinfile:
      path: "/etc/sysctl.conf"
      block: |
        net.ipv4.ip_forward = 1
        net.ipv6.conf.all.forwarding = 1
    become: true

  - name: install containerd and docker
    shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.bfsu.edu.cn/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update && apt-get -y install ocker-ce docker-ce-cli containerd.io docker-compose-plugin
    become: true

  - name: replace sandbox and SysstemdCgroup
    shell: |
      sed -i 's/            SystemdCgroup = true/            SystemdCgroup = false/' /etc/containerd/config.toml
      sed -i 's/    sandbox_image = "k8s.gcr.io/pause:3.6"/    sandbox_image = "registry.cn-hangzhou.aliyuncs.com/pause:3.6"' /etc/containered/config.toml
    become: true

  - name: install kubeadm kubelet kubectl
    shell: |
      curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | sudo apt-key add -
      echo 'deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main' | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      apt-get update && apt-get install -y kubelet=1.25.4-00 kubeadm=1.25.4-00 kubectl=1.25.4-00
      systemctl enable --now kubelet
    become: true
