- name: Install the Basic Software
  apt:
    name: ['bash-completion', 'conntrack', 'ipset', 'ipvsadm', 'jq', 'libseccomp2', 'nfs-common', 'psmisc', 'rsync', 'socat']
    state: present
  ignore_errors: true
